In [1]:
import pandas as pd
import random
import numpy as np
import matplotlib.pyplot as plt

#soru 1

In [2]:
#rasgele nominal değer oluşturma
x = ["fenerbahçe", "galatasaray", "beşiktaş", None]
tutulanTakimlar =  [random.choice(x) for _ in range(50)]

#rasgele ordinal değer oluşturma
y = ["lisans", "ön lisans", "doktora", "lise", "ilköğretim", None]
mezuniyetDereceleri =  [random.choice(y) for _ in range(50)]

#rasgele interval değer oluşturma
boylar = np.random.normal(1.75, 0.1, 50)

#rasgele ratio değer oluşturma
cocukSayilari = np.random.randint(0, 10, 50)

df = pd.DataFrame(data = {"tuttuğu takım":tutulanTakimlar, "mezuniyet derecesi":mezuniyetDereceleri, "boy": boylar, "çocuk sayısı": cocukSayilari})
df["boy"] = df["boy"].round(2)
df

   tuttuğu takım mezuniyet derecesi   boy  çocuk sayısı
0           None               lise  1.84             8
1           None             lisans  1.84             6
2     fenerbahçe            doktora  1.78             9
3     fenerbahçe               None  1.80             9
4       beşiktaş         ilköğretim  1.71             4
5    galatasaray               None  1.95             2
6    galatasaray               None  1.74             4
7    galatasaray               None  1.49             7
8       beşiktaş               lise  1.67             4
9       beşiktaş             lisans  1.91             0
10          None               lise  1.70             8
11      beşiktaş          ön lisans  1.75             3
12          None             lisans  1.84             0
13   galatasaray         ilköğretim  1.66             4
14   galatasaray          ön lisans  1.81             0
15   galatasaray            doktora  1.93             0
16    fenerbahçe         ilköğretim  1.93             9
17          None         ilköğretim  1.63             9
18      beşiktaş               lise  1.63             2
19          None               None  1.51             3
20   galatasaray            doktora  1.59             0
21          None         ilköğretim  1.69             0
22    fenerbahçe               None  1.67             8
23          None               lise  1.79             3
24      beşiktaş               None  1.72             7
25      beşiktaş         ilköğretim  1.72             3
26    fenerbahçe          ön lisans  1.95             2
27          None               None  1.60             8
28          None          ön lisans  1.80             5
29    fenerbahçe               None  1.71             3
30          None               None  1.69             4
31      beşiktaş            doktora  1.96             1
32          None          ön lisans  1.79             3
33          None         ilköğretim  1.67             8
34   galatasaray               None  1.82             3
35          None             lisans  1.65             6
36    fenerbahçe         ilköğretim  1.71             3
37          None         ilköğretim  1.73             6
38    fenerbahçe         ilköğretim  1.64             0
39          None          ön lisans  1.72             0
40      beşiktaş          ön lisans  1.71             7
41   galatasaray         ilköğretim  1.68             1
42          None             lisans  1.71             7
43          None               lise  1.91             8
44      beşiktaş               None  1.77             8
45    fenerbahçe          ön lisans  1.60             4
46   galatasaray             lisans  1.75             2
47   galatasaray               lise  1.71             7
48      beşiktaş          ön lisans  1.84             4
49          None         ilköğretim  1.81             9

#soru 2

In [3]:
df = pd.read_csv("data.csv")
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [4]:
print("Number Of Outlier value")
dfB = df[df["diagnosis"] == "B"]
for column in dfB.columns[2:]:
    desc = dfB[column].describe()
    Q1 = desc[4]
    Q3 = desc[6]
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    print(f"{column}: {dfB[(dfB[column] < lower_bound) | (dfB[column] > upper_bound)].radius_mean.size}", desc[2])

Number Of Outlier value
radius_mean: 3 1.7805116461410389
texture_mean: 18 3.995124593675911
perimeter_mean: 4 11.80743758010874
area_mean: 4 134.28711814705957
smoothness_mean: 4 0.013446077330274126
compactness_mean: 9 0.033749954593142575
concavity_mean: 12 0.0434421510450616
concave points_mean: 17 0.01590877837827477
symmetry_mean: 10 0.024806758206793282
fractal_dimension_mean: 17 0.006747342813925063
radius_se: 9 0.1125696081635206
texture_se: 12 0.5891797272308021
perimeter_se: 12 0.7711692027100456
area_se: 15 8.843472045083173
smoothness_se: 17 0.003060609649359842
compactness_se: 23 0.01635151136043786
concavity_se: 22 0.032918236251070425
concave points_se: 15 0.00570862467619159
symmetry_se: 10 0.006998538713378051
fractal_dimension_se: 26 0.00293821894019815
radius_worst: 2 1.9813675697080728
texture_worst: 10 5.493954523042769
perimeter_worst: 2 13.527090900564934
area_worst: 3 163.60142388916321
smoothness_worst: 3 0.020013465208022
compactness_worst: 10 0.09217997959811537
concavity_worst: 13 0.14036774077918968
concave points_worst: 2 0.0357973737756289
symmetry_worst: 3 0.041744766428705816
fractal_dimension_worst: 13 0.013804045110823396
Unnamed: 32: 0 nan

In [5]:
print("Number Of Outlier value")
dfM = df[df["diagnosis"] == "M"]
for column in dfM.columns[2:]:
    desc = dfM[column].describe()
    Q1 = desc[4]
    Q3 = desc[6]
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    print(f"{column}: {dfM[(dfM[column] < lower_bound) | (dfM[column] > upper_bound)].radius_mean.size}", desc[2])

Number Of Outlier value
radius_mean: 3 3.2039711007793663
texture_mean: 7 3.7794699207763403
perimeter_mean: 3 21.85465329107372
area_mean: 4 367.9379776066702
smoothness_mean: 3 0.012608235501058326
compactness_mean: 8 0.05398749505279829
concavity_mean: 6 0.07501932785025706
concave points_mean: 7 0.03437390887540152
symmetry_mean: 4 0.027638092143030164
fractal_dimension_mean: 1 0.007573315024808586
radius_se: 4 0.3450385808871092
texture_se: 7 0.48317807705374466
perimeter_se: 8 2.5685456540541707
area_se: 5 61.35526840853968
smoothness_se: 5 0.002890429930887557
compactness_se: 11 0.01838718992099185
concavity_se: 10 0.0216034283846679
concave points_se: 7 0.00551736244203068
symmetry_se: 16 0.010064888443904659
fractal_dimension_se: 9 0.0020414979342880577
radius_worst: 3 4.283569453482648
texture_worst: 4 5.434804076513243
perimeter_worst: 3 29.457055164129887
area_worst: 7 597.9677431516737
smoothness_worst: 4 0.021869834392199132
compactness_worst: 8 0.17037198471571027
concavity_worst: 6 0.18150672252420566
concave points_worst: 2 0.04630779007517738
symmetry_worst: 7 0.07468495606861252
fractal_dimension_worst: 4 0.021552888514426563
Unnamed: 32: 0 nan

#soru 3

In [6]:
df = df[["radius_mean", "area_mean", "compactness_mean"]]
df.corr()

                  radius_mean  area_mean  compactness_mean
radius_mean          1.000000   0.987357          0.506124
area_mean            0.987357   1.000000          0.498502
compactness_mean     0.506124   0.498502          1.000000

In [7]:
df = df[["radius_mean", "area_mean", "compactness_mean"]]
df.cov()

                  radius_mean      area_mean  compactness_mean
radius_mean         12.418920    1224.483409          0.094197
area_mean         1224.483409  123843.554318          9.264931
compactness_mean     0.094197       9.264931          0.002789

In [8]:
df = df[["radius_mean", "area_mean", "compactness_mean"]]
df.corr(method='pearson')

                  radius_mean  area_mean  compactness_mean
radius_mean          1.000000   0.987357          0.506124
area_mean            0.987357   1.000000          0.498502
compactness_mean     0.506124   0.498502          1.000000

#soru 3 pearson için
radius mean ve area mean birbiri ile yüksek pozitif korelasyona sahip biri artarken diğeri de artıyor.

compactness mean ise diğer iki durum ile 0.5'e yakın ortalama bir korelasyona sahip.

In [9]:
df = df[["radius_mean", "area_mean", "compactness_mean"]]
df.corr(method="spearman")

                  radius_mean  area_mean  compactness_mean
radius_mean          1.000000   0.999602          0.497578
area_mean            0.999602   1.000000          0.488988
compactness_mean     0.497578   0.488988          1.000000

#soru 3
spearman için

radius mean ve area mean birbiri ile yüksek pozitif korelasyona sahip biri artarken diğeri de artıyor.

compactness mean ise diğer iki durum ile 0.5'e yakın ortalama bir korelasyona sahip.

#soru 4

1)Hasta ve sağlıklı insanlara yapılan hasta mı değil mi testleri

2)Havanın bulutlu olduğu ve olmadığı günlerde yağmur yağma olasılığı

3)bir üretim bandında hata tespit eden cihazın hatalı dediği ürünlerin gerçekten hatalı olup olmama durumu

4)yalan tespit makinesine bağlı insanın söylediği cümlelerin doğru ve yanlış olma durumunun yalan makinesi ile tespiti

5)bir öğrencinin derste başarılı olup olmadığını derse düzenli katılıp katılmadığın bilinmesi durumunda tahmini

#soru 5

	------------Poisson-----Normal-----Gamma-----Weilbull-----Logaritmik
Ayrık / Sürekli---------Ayrık-----------Sürekli----------Sürekli-------Sürekli---------------Ayrık

Negatif değer----------Almaz----------Alabilir-----------Almaz----------Almaz-----------Almaz

Alt limit----------------------0--------------Yok----------------0--------------0-----------------------0

Üst limit-------------------Yok-------------Yok---------------Yok------------Yok------------------Yok

Simetrik--------------Yüksek

Simetrik------------Ortalamalar------Her Zaman-----------Değil----------Değil----------------Değil

------------------------İçin